// <auto-generated />
using System;
using APILocacao.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APILocacao.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220711170224_Innicial Migration")]
    partial class InnicialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("APILocacao.Models.Client", b =>
                {
                    b.Property<ulong>("CPF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Lastname")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Telephone")
                        .HasColumnType("longtext");

                    b.HasKey("CPF");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("APILocacao.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Director")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Synopsis")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("APILocacao.Models.RentMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<ulong?>("ClientsCPF")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("FinalDeliveryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MoviesId")
                        .HasColumnType("int");

                    b.Property<bool>("ReturnMovie")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("TotalRent")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ClientsCPF");

                    b.HasIndex("MoviesId");

                    b.ToTable("RentMovies");
                });

            modelBuilder.Entity("APILocacao.Models.RentMovie", b =>
                {
                    b.HasOne("APILocacao.Models.Client", "Clients")
                        .WithMany()
                        .HasForeignKey("ClientsCPF");

                    b.HasOne("APILocacao.Models.Movie", "Movies")
                        .WithMany()
                        .HasForeignKey("MoviesId");

                    b.Navigation("Clients");

                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
